---
title: "Hands-on Exercise 4"
subtitle: ""
author: "Wang Yuhui"
date: "May 4, 2024"
date-modified: "last-modified"
execute: 
  eval: true
  echo: true
  warning: false
  freeze: true
---

```{r}
pacman::p_load(tidyverse, ggstatsplot)
```

```{r}
exam <- read_csv('data/Exam_data.csv')
```

```{r}
set.seed(1234)

p <- gghistostats(
      data = exam,
      x = ENGLISH,
      type = "parametric",
      test.value = 60,
      bin.args = list(color = 'black',
                  xlab = "English scores")
)
p
```

```{r}
extract_stats(p)
```

```{r}
exam_long <- exam %>%
  pivot_longer(
    cols = ENGLISH:SCIENCE,
    names_to = 'SUBJECT',
    values_to = 'SCORES')%>%
  filter(CLASS == "3A")
```

```{r}
ggwithinstats(
  data = filter(exam_long,
                SUBJECT %in%
                  c("MATHS", "SCIENCE")),
  x = SUBJECT,
  y = SCORES,
  type = "p"
)
```

```{r}
ggscatterstats(
  data = exam,
  x = MATHS,
  y = ENGLISH,
  marginal = TRUE,
  label.var = ID,
  label.expression = ENGLISH >90 & MATHS >90,
)
```
